apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo-fargate
  namespace: default
spec:
 replicas: 1
 selector:
   matchLabels:
     app: "nginx-demo-fargate"
 template:
   metadata:
     labels:
       app: "nginx-demo-fargate"
     name: "nginx-demo-fargate-pod"
     annotations:
       ad.datadoghq.com/nginx-demo-ctr.check_names: '["nginx"]'
       ad.datadoghq.com/nginx-demo-ctr.init_configs: '[{}]'
       ad.datadoghq.com/nginx-demo-ctr.instances: '[{"nginx_status_url": "http://%%host%%:80/nginx_status/"}]'
   spec:
     serviceAccountName: datadog-agent
     volumes:
       - name: "config"
         configMap:
           name: "nginxconfig"
       - name: "ddconfig"
         configMap:
           name: "ddconfigmap"
       - name: app-logs
         emptyDir: {}
       - name: fluent-bit-config
         configMap:
           name: fluent-bit-config
     containers:
     - name: nginx-demo-ctr
       image: nginx
       resources:
         limits:
           cpu: "2"
         requests:
           cpu: "1.5"
       ports:
       - containerPort: 81
       volumeMounts:
       - name: "config"
         mountPath: "/etc/nginx/nginx.conf"
         subPath: "nginx.conf"
       - name: "ddconfig"
         mountPath: "/etc/nginx/dd-config.conf"
         subPath: "dd-config.conf"
       - mountPath: /var/log/containers
         name: app-logs
       env:
         - name: DD_AGENT_HOST
           valueFrom:
             fieldRef:
               fieldPath: status.hostIP
         - name: DATADOG_TRACE_AGENT_HOSTNAME
           valueFrom:
             fieldRef:
               fieldPath: status.hostIP
       command: ["/bin/sh"]
       args: ["-c", "apt-get update && apt-get -y install wget; wget https://github.com/opentracing-contrib/nginx-opentracing/releases/download/v0.10.0/linux-amd64-nginx-1.17.3-ngx_http_module.so.tgz; tar zxf linux-amd64-nginx-1.17.3-ngx_http_module.so.tgz -C /usr/lib/nginx/modules; wget https://github.com/DataDog/dd-opentracing-cpp/releases/download/v1.2.0/linux-amd64-libdd_opentracing_plugin.so.gz; gunzip linux-amd64-libdd_opentracing_plugin.so.gz -c > /usr/local/lib/libdd_opentracing_plugin.so"]
     - name: fluent-bit
       image: fluent/fluent-bit:latest
       volumeMounts:
       - name: fluent-bit-config
         mountPath: "/fluent-bit/etc"
       - name: app-logs
         mountPath: /var/log/containers
       resources:
         limits:
           memory: 500Mi
         requests:
           cpu: 500m
           memory: 100Mi
     ## Running the Agent as a sidecar
     - name: datadog-agent
       image: datadog/agent
       ports:
         - containerPort: 8126
           name: traceport
           protocol: TCP
       env:
         - name: DD_API_KEY
           value: "<MY_DATADOG_API_KEY>"
           ## Set DD_SITE to "datadoghq.eu" to send your
           ## Agent data to the Datadog EU site
         - name: DD_SITE
           value: "datadoghq.com"
         - name: DD_EKS_FARGATE
           value: "true"
         - name: DD_KUBERNETES_KUBELET_NODENAME
           valueFrom:
             fieldRef:
               apiVersion: v1
               fieldPath: spec.nodeName
         - name: DD_APM_ENABLED
           value: "true"
         - name: DD_APM_NON_LOCAL_TRAFFIC
           value: "true"
         - name: DD_TAGS
           value: "env:gobtest"
       resources:
         requests:
           memory: "512Mi"
           cpu: "800m"
         limits:
           memory: "512Mi"
           cpu: "800m"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ddconfigmap
  namespace: default
data:
  dd-config.conf: |+
    {
      "service": "nginx",
      "operation_name_override": "nginx.handle",
      "agent_host": "dd-agent",
      "agent_port": 8126
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginxconfig
  namespace: default
data:
  nginx.conf: |+

    load_module modules/ngx_http_opentracing_module.so;
    events {
        worker_connections  1024;
    }
    http {
        opentracing_load_tracer /usr/local/lib/libdd_opentracing_plugin.so /etc/nginx/dd-config.json;
        opentracing on;
        opentracing_tag http_user_agent $http_user_agent;
        opentracing_trace_locations off;
        opentracing_operation_name "$request_method $uri";
        log_format with_trace_id '$remote_addr - $http_x_forwarded_user [$time_local] "$request" '
            '$status $body_bytes_sent "$http_referer" '
            '"$http_user_agent" "$http_x_forwarded_for" '
            '"$opentracing_context_x_datadog_trace_id" "$opentracing_context_x_datadog_parent_id"';
        access_log /var/log/containers/access.log with_trace_id;
        error_log /var/log/containers/error.log info;
        server {
            listen       80;
            server_name  localhost;
            location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
                opentracing_tag "custom-tag" "special value";
            }
            location /test {
                alias /usr/share/nginx/html/index.html;
            }
            location /nginx_status {
              stub_status on;
              access_log off;
              allow all;
            }
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  labels:
    app.kubernetes.io/name: fluentbit
data:
  fluent-bit.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
    [OUTPUT]
        Name           datadog
        Match          *
        Host           http-intake.logs.datadoghq.com
        TLS            on
        apikey         <MY_DATADOG_API_KEY>
        dd_service     my-web-app
        dd_source      nginx
        dd_tags        env:gobtest
